<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyVersion>2.6.19.0</AssemblyVersion>
    <FileVersion>2.6.19.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.HtmlRenderer" Version="11.2.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Markdig" Version="0.45.0" />
    <!-- <PackageReference Include="Material.Avalonia" Version="3.9.2" /> -->
    <PackageReference Include="Semi.Avalonia" Version="11.3.7.3" />
  </ItemGroup>

  <ItemGroup>
    <!-- Include all files from the Resources folder as embedded resources -->
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>

  <Target Name="BuildUpdater" AfterTargets="Build">
    <MSBuild Projects="$(MSBuildThisFileDirectory)..\TazUOUpdater\TazUOUpdater.csproj"
             Targets="Restore;Build"
             Properties="Configuration=$(Configuration);OutputPath=$(TargetDir)\update" />
  </Target>

  <Target Name="PublishUpdater" AfterTargets="Publish">
    <ConvertToAbsolutePath Paths="$(PublishDir)">
      <Output TaskParameter="AbsolutePaths" PropertyName="AbsolutePublishDir" />
    </ConvertToAbsolutePath>
    <MSBuild Projects="$(MSBuildThisFileDirectory)..\TazUOUpdater\TazUOUpdater.csproj"
             Targets="Restore;Publish"
             Properties="Configuration=$(Configuration);PublishDir=$(AbsolutePublishDir)\update;RuntimeIdentifier=$(RuntimeIdentifier)" />
  </Target>
</Project>
